#include <iostream>
using namespace std;

int main() 
{
    // Define the total sales and the percentage generated by the East Coast division
    double totalSales = 8.6e6; // $8.6 million
    double eastCoastPercentage = 0.58; // 58 percent

    // Calculate the sales generated by the East Coast division
    double eastCoastSales = totalSales * eastCoastPercentage;

    // Display the predicted sales for the East Coast division
    cout << "The East Coast division is predicted to generate $" << eastCoastSales << " in sales this year." << endl;

    return 0;
}

